spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: mysecretpassword
    initialize: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true