spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      user: root
      password: super!secret88
      database: testdb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
